// let allButtonMenu = document.getElementById("allButtonMenu")
// let allButtonBody = document.getElementById("allButtonBody")
// let searchPositiveEffectButton = document.getElementById("searchPositiveEffectButton")
// let searchMedicalEffectButton  = document.getElementById("searchMedicalEffectButton")
// let searchNegativeEffectButton  = document.getElementById("searchNegativeEffectButton")
// let searchFlavorButton = document.getElementById("searchFlavorButton")
// let nameButton = document.getElementById("nameButton")
// let displayDiv = document.getElementById("displayDiv")